#pragma once
#include <string>
#include <cmath>
#include <vector>

namespace Common
{
    enum class ECAVERN_SPRITES : std::uint8_t
    {
        EMPTY,
        BACKGROUND_0,
        BACKGROUND_1,
        BACKGROUND_2,
        BACKGROUND_3,
        BLOCK_0,
        BLOCK_1,
        BLOCK_2,
        BLOCK_3,
        BLOW_0,
        BLOW_1,
        BOLT_00,
        BOLT_01,
        BOLT_10,
        BOLT_11,
        FALL_0,
        FALL_1,
        FONT_48,
        FONT_49,
        FONT_50,
        FONT_51,
        FONT_52,
        FONT_53,
        FONT_54,
        FONT_55,
        FONT_56,
        FONT_57,
        FONT_65,
        FONT_66,
        FONT_67,
        FONT_68,
        FONT_69,
        FONT_70,
        FONT_71,
        FONT_72,
        FONT_73,
        FONT_74,
        FONT_75,
        FONT_76,
        FONT_77,
        FONT_78,
        FONT_79,
        FONT_80,
        FONT_81,
        FONT_82,
        FONT_83,
        FONT_84,
        FONT_85,
        FONT_86,
        FONT_87,
        FONT_88,
        FONT_89,
        FONT_90,
        FRUIT_00,
        FRUIT_01,
        FRUIT_02,
        FRUIT_10,
        FRUIT_11,
        FRUIT_12,
        FRUIT_20,
        FRUIT_21,
        FRUIT_22,
        FRUIT_30,
        FRUIT_31,
        FRUIT_32,
        FRUIT_40,
        FRUIT_41,
        FRUIT_42,
        JUMP_0,
        JUMP_1,
        LIFE,
        ORB_0,
        ORB_1,
        ORB_2,
        ORB_3,
        ORB_4,
        ORB_5,
        ORB_6,
        OVER,
        PLUS,
        POP_0,
        POP_1,
        POP_2,
        POP_3,
        POP_4,
        POP_5,
        POP_10,
        POP_11,
        POP_12,
        POP_13,
        POP_14,
        RECOIL_0,
        RECOIL_1,
        ROBOT_001,
        ROBOT_002,
        ROBOT_003,
        ROBOT_004,
        ROBOT_005,
        ROBOT_006,
        ROBOT_007,
        ROBOT_010,
        ROBOT_011,
        ROBOT_012,
        ROBOT_013,
        ROBOT_014,
        ROBOT_015,
        ROBOT_016,
        ROBOT_017,
        ROBOT_101,
        ROBOT_102,
        ROBOT_103,
        ROBOT_104,
        ROBOT_105,
        ROBOT_106,
        ROBOT_107,
        ROBOT_110,
        ROBOT_111,
        ROBOT_112,
        ROBOT_113,
        ROBOT_114,
        ROBOT_115,
        ROBOT_116,
        ROBOT_117,
        RUN_00,
        RUN_01,
        RUN_02,
        RUN_03,
        RUN_10,
        RUN_11,
        RUN_12,
        RUN_13,
        SPACE_0,
        SPACE_1,
        SPACE_2,
        SPACE_3,
        SPACE_4,
        SPACE_5,
        SPACE_6,
        SPACE_7,
        SPACE_8,
        SPACE_9,
        STAND_0,
        STAND_1,
        STILL,
        TITLE,
        TRAP_00,
        TRAP_01,
        TRAP_02,
        TRAP_03,
        TRAP_04,
        TRAP_05,
        TRAP_06,
        TRAP_07,
        TRAP_10,
        TRAP_11,
        TRAP_12,
        TRAP_13,
        TRAP_14,
        TRAP_15,
        TRAP_16,
        TRAP_17
    };

    enum class ECAVERN_SOUNDS : std::uint8_t
    {
        APPEAR_0,
        BLOW_0,
        BLOW_1,
        BLOW_2,
        BLOW_3,
        BONUS_0,
        DIE_0,
        JUMP_0,
        LAND_0,
        LAND_1,
        LAND_2,
        LAND_3,
        LASER_0,
        LASER_1,
        LASER_2,
        LASER_3,
        LEVEL_0,
        LIFE_0,
        OUCH_0,
        OUCH_1,
        OUCH_2,
        OUCH_3,
        OVER_0,
        POP_0,
        POP_1,
        POP_2,
        POP_3,
        TRAP_0,
        TRAP_1,
        TRAP_2,
        TRAP_3,
        SCORE_0,
        VANISH_0
    };

    enum class ECAVERN_MUSIC : std::uint8_t
    {
        THEME
    };

    const std::string TITLE = "Cavern";

    constexpr int WIDTH = 800;
    constexpr int HEIGHT = 480;

    constexpr int NUM_ROWS = 18;
    constexpr int NUM_COLUMNS = 28;
    constexpr int LEVEL_X_OFFSET = 50;
    constexpr int GRID_BLOCK_SIZE = 25;
    //const Anchor ANCHOR_CENTRE = { "center", "center" };
    //const Anchor ANCHOR_CENTRE_BOTTOM = { "center", "bottom" };
    const std::vector<std::vector<std::string>> LEVELS = { {"XXXXX     XXXXXXXX     XXXXX",
                                                            "", "", "", "",
                                                            "   XXXXXXX        XXXXXXX   ",
                                                            "", "", "",
                                                            "   XXXXXXXXXXXXXXXXXXXXXX   ",
                                                            "", "", "",
                                                            "XXXXXXXXX          XXXXXXXXX",
                                                            "", "", ""},

                                                            {"XXXX    XXXXXXXXXXXX    XXXX",
                                                            "", "", "", "",
                                                            "    XXXXXXXXXXXXXXXXXXXX    ",
                                                            "", "", "",
                                                            "XXXXXX                XXXXXX",
                                                            "      X              X      ",
                                                            "       X            X       ",
                                                            "        X          X        ",
                                                            "         X        X         ",
                                                            "", "", ""},

                                                            {"XXXX    XXXX    XXXX    XXXX",
                                                            "", "", "", "",
                                                            "  XXXXXXXX        XXXXXXXX  ",
                                                            "", "", "",
                                                            "XXXX      XXXXXXXX      XXXX",
                                                            "", "", "",
                                                            "    XXXXXX        XXXXXX    ",
                                                            "", "", ""} };
}